import Foundation
import PackagePlugin

/// Generates `SceneRegistry.swift` for the CLI by scanning the SwiftRender
/// target for `public struct X: <SceneProtocol>`. Adding a scene file is the
/// only step — no hand-edited dictionary, no merge conflicts on it.
@main
struct SceneRegistryPlugin: BuildToolPlugin {
    static let protocols: Set<String> = ["RenderScene", "AudioReactiveScene", "PropsScene", "PropsAudioScene"]

    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        guard let lib = context.package.targets.first(where: { $0.name == "SwiftRender" }) as? SourceModuleTarget
        else { return [] }
        let files = lib.sourceFiles(withSuffix: "swift").map(\.path).sorted { $0.string < $1.string }

        let decl = try NSRegularExpression(pattern: #"public\s+struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([^{]+)\{"#)
        var names: [String] = []
        for file in files {
            guard let src = try? String(contentsOfFile: file.string, encoding: .utf8) else { continue }
            let ns = src as NSString
            for m in decl.matches(in: src, range: NSRange(location: 0, length: ns.length)) {
                let name = ns.substring(with: m.range(at: 1))
                let clause = ns.substring(with: m.range(at: 2))
                let conforms = clause.split(whereSeparator: { ",: \n\t".contains($0) }).map(String.init)
                if conforms.contains(where: Self.protocols.contains) { names.append(name) }
            }
        }
        names = Array(Set(names)).sorted()

        let body = names.map { "    \"\($0)\": SceneRunner(\($0).self)," }.joined(separator: "\n")
        let source = """
        // Generated by SceneRegistryPlugin from the SwiftRender target — do not edit.
        import SwiftRender

        @MainActor let generatedSceneRunners: [String: SceneRunner] = [
        \(body.isEmpty ? "    :" : body)
        ]

        """
        let out = context.pluginWorkDirectory.appending("SceneRegistry.swift")
        return [.buildCommand(
            displayName: "Generating scene registry (\(names.count) scenes)",
            executable: Path("/bin/sh"),
            arguments: ["-c", "printf '%s' \"$1\" > \"$2\"", "sh", source, out.string],
            inputFiles: files,
            outputFiles: [out]
        )]
    }
}
