#!/usr/bin/env python3
"""Build and bundle the native SwiftRender Studio Mac app (Python standard library)."""

import argparse
import json
import os
import plistlib
import shutil
import subprocess
import sys
import tempfile
import uuid
from pathlib import Path


REPOSITORY = Path(__file__).resolve().parents[2]
PRODUCT = "swift-render-studio"
EXECUTABLE = "SwiftRenderStudio"
BUNDLE_ID = "design.anoop.swiftrender.studio"
VERSION = "0.1.0"
MARKER = ".swift-render-studio-build.json"
PRODUCER = "swift-render-studio-bundler"
WORKFLOW = REPOSITORY / "codex-plugin" / "skills" / "app-launch-video"
EXCLUDED_DIRECTORIES = {
    ".git", ".build", ".swiftpm", "__pycache__", ".pytest_cache", ".mypy_cache",
    ".venv", "venv", "node_modules", "build", "tests", "out", "output", "tmp", "temp",
}
EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".swp", ".swo", ".tmp", ".log"}
MACH_O_HEADERS = {
    b"\xfe\xed\xfa\xce", b"\xce\xfa\xed\xfe", b"\xfe\xed\xfa\xcf", b"\xcf\xfa\xed\xfe",
    b"\xca\xfe\xba\xbe", b"\xbe\xba\xfe\xca", b"\xca\xfe\xba\xbf", b"\xbf\xba\xfe\xca",
}


class BuildError(RuntimeError):
    pass


def run(arguments, capture=False):
    """Use argv throughout: repository/output names may contain shell metacharacters."""
    try:
        result = subprocess.run(
            [str(argument) for argument in arguments], cwd=REPOSITORY,
            check=True, text=True, stdout=subprocess.PIPE if capture else None,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise BuildError("Command failed: {} ({})".format(arguments[0], exc)) from exc
    return result.stdout.strip() if capture else None


def normalize_output(value):
    path = Path(os.path.abspath(os.path.expanduser(str(value))))
    if path.suffix.lower() != ".app":
        raise BuildError("--output must name a .app bundle")
    if path.is_symlink():
        raise BuildError("Refusing to replace a symlink at the app output")
    # Resolve the parent, not a pre-existing final bundle. This keeps the symlink
    # refusal meaningful and puts staging/backup on the destination filesystem.
    normalized = path.parent.resolve() / path.name
    if WORKFLOW.resolve() in normalized.parents:
        raise BuildError("App output must be outside the bundled workflow source tree")
    return normalized


def verify_replaceable(output, overwrite):
    if not output.exists():
        return
    if not overwrite:
        raise BuildError("Output already exists; use --overwrite to replace a bundle made by this tool")
    if not output.is_dir() or output.is_symlink():
        raise BuildError("Existing output is not a regular generated app bundle")
    try:
        marker = json.loads((output / "Contents" / MARKER).read_text(encoding="utf-8"))
        with (output / "Contents" / "Info.plist").open("rb") as stream:
            info = plistlib.load(stream)
    except (OSError, ValueError, plistlib.InvalidFileException) as exc:
        raise BuildError("Existing output has no valid SwiftRender Studio build marker; choose another output") from exc
    if not isinstance(marker, dict) or not isinstance(info, dict):
        raise BuildError("Existing output has malformed build metadata; choose another output")
    if marker.get("producer") != PRODUCER or marker.get("bundleIdentifier") != BUNDLE_ID or info.get("CFBundleIdentifier") != BUNDLE_ID:
        raise BuildError("Existing output is not a bundle generated by this tool; choose another output")


def excluded_file(path):
    return path.name == ".DS_Store" or path.name.startswith(".env") or path.name.endswith("~") or path.suffix.lower() in EXCLUDED_SUFFIXES


def copy_workflow(source, destination):
    for required in ("SKILL.md", "scripts/launch.py", "assets/NativeStarter/Package.swift"):
        if not (source / required).is_file():
            raise BuildError("Workflow is incomplete: missing {}".format(required))
    copied = 0
    for directory, directories, filenames in os.walk(source, followlinks=False):
        current = Path(directory)
        directories[:] = sorted(name for name in directories if name.lower() not in EXCLUDED_DIRECTORIES)
        for name in directories:
            if (current / name).is_symlink():
                raise BuildError("Workflow must not include directory symlinks: {}".format((current / name).relative_to(source)))
        for name in sorted(filenames):
            path = current / name
            if excluded_file(path):
                continue
            if path.is_symlink() or not path.is_file():
                raise BuildError("Workflow must contain regular files: {}".format(path.relative_to(source)))
            target = destination / path.relative_to(source)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
            target.chmod(0o644)
            copied += 1
    return copied


def make_info():
    return {
        "CFBundleDevelopmentRegion": "en",
        "CFBundleDisplayName": "SwiftRender Studio",
        "CFBundleExecutable": EXECUTABLE,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": "SwiftRender Studio",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": "1",
        "LSMinimumSystemVersion": "14.0",
        "NSHighResolutionCapable": True,
        "NSPrincipalClass": "NSApplication",
    }


def locate_binary(configuration, skip_build, binary):
    if binary is not None and not skip_build:
        raise BuildError("--binary requires --skip-build")
    if not skip_build:
        run(["swift", "build", "--product", PRODUCT, "--configuration", configuration])
    if binary is None:
        bin_path = run(["swift", "build", "--show-bin-path", "--configuration", configuration], capture=True)
        binary = Path(bin_path) / PRODUCT
    binary = Path(binary).expanduser().resolve()
    if not binary.is_file():
        raise BuildError("Executable not found: {}".format(binary))
    with binary.open("rb") as stream:
        if stream.read(4) not in MACH_O_HEADERS:
            raise BuildError("Executable must be a compiled Mach-O Mac binary: {}".format(binary))
    return binary


def clean_signing_attributes(app):
    """Clean only signing-prohibited metadata on the fresh copied bundle.

    Finder/File Provider can add these attributes even when copyfile() copies no
    source xattrs. Never strip unrelated attributes or touch the input workflow.
    """
    forbidden = {"com.apple.ResourceFork", "com.apple.FinderInfo"}
    removed = 0
    for directory, directories, files in os.walk(app, followlinks=False):
        current = Path(directory)
        for path in [current] + [current / name for name in files]:
            if path.is_symlink():
                raise BuildError("Fresh app bundle unexpectedly contains a symlink")
            # Apple's bundled Python may not expose os.listxattr/removexattr.
            # The system xattr tool is present on macOS; list names only so no
            # arbitrary metadata contents are read into logs.
            attributes = run(["/usr/bin/xattr", path], capture=True).splitlines()
            for attribute in attributes:
                if attribute in forbidden:
                    run(["/usr/bin/xattr", "-d", attribute, path])
                    removed += 1
        if any((current / name).is_symlink() for name in directories):
            raise BuildError("Fresh app bundle unexpectedly contains a directory symlink")
    return removed


def install_staged(staged, output, overwrite, verify=None):
    # Recheck after a potentially long build so a new user-created directory is
    # never silently replaced. Keep the old generated bundle until rename works.
    verify_replaceable(output, overwrite)
    backup = None
    if output.exists():
        backup = output.with_name(".{}-backup-{}".format(output.name, uuid.uuid4().hex))
        os.replace(output, backup)
    installed = False
    try:
        os.replace(staged, output)
        installed = True
        if verify is not None:
            verify(output)
    except (OSError, BuildError):
        if installed:
            os.replace(output, staged)
        if backup is not None:
            os.replace(backup, output)
        raise
    if backup is not None:
        try:
            shutil.rmtree(backup)
        except OSError as exc:
            print("App installed; retained old bundle at {}: {}".format(backup, exc), file=sys.stderr)


def bundle(binary, output, configuration, overwrite):
    verify_replaceable(output, overwrite)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=".swift-render-studio-", dir=output.parent))
    signed = False
    removed_attributes = 0
    try:
        staged = temporary / output.name
        contents = staged / "Contents"
        macos = contents / "MacOS"
        macos.mkdir(parents=True)
        shutil.copyfile(binary, macos / EXECUTABLE)
        (macos / EXECUTABLE).chmod(0o755)
        copied = copy_workflow(WORKFLOW, contents / "Resources" / "Workflow")
        with (contents / "Info.plist").open("wb") as stream:
            plistlib.dump(make_info(), stream, sort_keys=True)
        # Deliberately no developer home paths or source paths in bundle metadata.
        (contents / MARKER).write_text(json.dumps({
            "producer": PRODUCER, "schemaVersion": 1, "bundleIdentifier": BUNDLE_ID,
            "version": VERSION, "configuration": configuration,
        }, indent=2) + "\n", encoding="utf-8")
        codesign = Path("/usr/bin/codesign")
        if codesign.is_file():
            removed_attributes += clean_signing_attributes(staged)
            run([codesign, "--force", "--deep", "--sign", "-", staged])
            run([codesign, "--verify", "--deep", "--strict", staged])
            signed = True
        def verify_installed(path):
            nonlocal removed_attributes
            if signed:
                removed_attributes += clean_signing_attributes(path)
                run([codesign, "--verify", "--deep", "--strict", path])
        install_staged(staged, output, overwrite, verify=verify_installed)
    except BuildError as exc:
        if "codesign" in str(exc):
            raise BuildError("{}. If this destination is managed by iCloud/File Provider, retry with --output in a local folder outside that provider.".format(exc)) from exc
        raise
    finally:
        shutil.rmtree(temporary, ignore_errors=True)
    return {"app": str(output), "version": VERSION, "configuration": configuration,
            "workflowFiles": copied, "adHocSigned": signed, "notarized": False,
            "removedSigningAttributes": removed_attributes}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=REPOSITORY / "out" / "SwiftRender Studio.app")
    parser.add_argument("--debug", action="store_true", help="Use the debug configuration instead of release")
    parser.add_argument("--skip-build", action="store_true", help="Bundle an existing executable without building")
    parser.add_argument("--binary", type=Path, help="Explicit existing executable; requires --skip-build")
    parser.add_argument("--overwrite", action="store_true", help="Replace only a previous bundle generated by this tool")
    parser.add_argument("--open", action="store_true", help="Launch the successfully bundled app")
    args = parser.parse_args()
    try:
        if sys.platform != "darwin":
            raise BuildError("SwiftRender Studio must be built and bundled on macOS")
        output = normalize_output(args.output)
        verify_replaceable(output, args.overwrite)
        configuration = "debug" if args.debug else "release"
        binary = locate_binary(configuration, args.skip_build, args.binary)
        result = bundle(binary, output, configuration, args.overwrite)
        if args.open:
            run(["/usr/bin/open", output])
        print(json.dumps(result, indent=2))
    except (BuildError, OSError) as exc:
        print("Cannot bundle SwiftRender Studio: {}".format(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
